In [9]:
import pandas as pd
import numpy as np

In [10]:
file = '..//data//nsduh_with_final_column.csv'
main_data = pd.read_csv(file, sep=',')

In [23]:
main_data.head()

,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,CG30EST,CIG30AV,...,GOVTPROG,INCOME,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP4,MAIIN102,AIIND102,RISKGR
0,1,99,99,13,9999,99,4,93,93,93,...,2,4,3.0,2,2,1,1,2,2,0
1,1,99,99,15,9999,99,1,18,99,4,...,2,2,3.0,1,2,1,1,2,2,2
2,1,99,99,14,9999,99,1,10,99,3,...,2,4,3.0,2,2,1,1,2,2,2
3,1,99,99,16,9999,99,4,93,93,93,...,2,4,3.0,2,2,2,2,2,2,2
4,2,99,99,991,9991,91,91,91,91,91,...,2,2,3.0,1,1,1,1,2,2,0

In [13]:
main_data.groupby('RISKGR').groups

{0: Int64Index([    0,     4,     6,     8,     9,    11,    13,    16,    17,
                19,
             ...
             56245, 56255, 56256, 56257, 56262, 56264, 56266, 56271, 56272,
             56273],
            dtype='int64', length=22301),
 1: Int64Index([    5,    10,    12,    14,    31,    34,    35,    36,    39,
                41,
             ...
             56250, 56253, 56258, 56260, 56263, 56267, 56269, 56270, 56274,
             56275],
            dtype='int64', length=19467),
 2: Int64Index([    1,     2,     3,     7,    15,    18,    20,    24,    25,
                28,
             ...
             56236, 56246, 56247, 56251, 56252, 56254, 56259, 56261, 56265,
             56268],
            dtype='int64', length=14508)}

In [12]:
x_ss = main_data.drop('RISKGR',axis=1)
# x_mm = main_data.drop('RISKGR',axis=1)
y = main_data['RISKGR']

### Standarization

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()
scaler.fit(x_ss)
scaled_features_ss = scaler.transform(x_ss)

C:\Users\Daria\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Daria\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until

In [24]:
scaled_features_ss

array([[-1.03005556,  0.52273463,  0.5226434 , ..., -0.98397146,
         0.13457137,  0.13484485],
       [-1.03005556,  0.52273463,  0.5226434 , ..., -0.98397146,
         0.13457137,  0.13484485],
       [-1.03005556,  0.52273463,  0.5226434 , ..., -0.98397146,
         0.13457137,  0.13484485],
       ...,
       [ 0.97082141, -1.90881409, -1.91011928, ...,  0.3167421 ,
         0.13457137,  0.13484485],
       [-1.03005556,  0.52273463,  0.5226434 , ...,  0.3167421 ,
         0.13457137,  0.13484485],
       [ 0.97082141,  0.52273463,  0.5226434 , ..., -0.98397146,
         0.13457137,  0.13484485]])

### MinMax Scaler

In [10]:
# from sklearn.preprocessing import MinMaxScaler

In [11]:
# scaler_mm = MinMaxScaler()
# scaler_mm.fit(x_mm)
# scaled_features_mm = scaler_mm.transform(x_mm)

C:\Users\Daria\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [12]:
# scaled_features_mm

array([[0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [1.        , 0.03061224, 0.03061224, ..., 0.5       , 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.5       , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ]])

### PCA extraction

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca_ss = PCA(n_components=0.85)
# pca_mm = PCA(n_components=0.85)

In [27]:
reduced_ss = pca_ss.fit_transform(scaled_features_ss)
# reduced_mm = pca_mm.fit_transform(scaled_features_mm)

In [28]:
reduced_data = pd.DataFrame(reduced_ss)
reduced_data.head()

,0,1,2,3,4,5,6,7,8,9,...,252,253,254,255,256,257,258,259,260,261
0,4.161882,-9.325109,-0.373126,-0.052808,-0.698259,4.933511,-2.140699,0.869421,0.038036,0.954849,...,0.985914,0.649631,-0.670733,-0.711541,-0.832681,-1.388345,0.117794,0.454118,-1.059230,0.423132
1,9.674925,-3.581752,-4.303914,-10.333025,5.763884,-6.214472,6.969558,-7.564769,0.817216,-3.354259,...,-0.336745,0.273793,-0.230721,0.423103,-0.637623,-0.790577,0.122406,0.007787,-0.214282,0.065505
2,10.236991,-6.791700,-3.447423,-10.103987,5.758740,-3.635738,5.683193,-7.229738,0.302514,-2.057853,...,0.332653,-0.583463,0.072254,0.707858,-0.396691,0.453304,0.206835,-0.161873,0.628871,0.398236
3,3.540502,-10.364173,-2.053337,-2.910695,-0.762153,5.800408,-2.332828,0.825269,0.134046,-0.889574,...,0.443561,-0.089045,-0.561901,0.211767,-0.305955,0.183721,0.090307,0.240883,0.435638,0.178456
4,-6.848046,-4.969237,11.457287,-0.199674,-5.355195,1.820314,0.473076,-3.146023,-1.440604,8.725895,...,0.171669,-0.308272,0.091469,0.359798,-0.463577,-0.885558,-0.313491,0.438535,-0.455354,-0.039124

In [24]:
# reduced_data_mm = pd.DataFrame(reduced_mm)
# reduced_data_mm.head()

In [13]:
# reduced_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56276 entries, 0 to 56275
Data columns (total 21 columns):
0     56276 non-null float64
1     56276 non-null float64
2     56276 non-null float64
3     56276 non-null float64
4     56276 non-null float64
5     56276 non-null float64
6     56276 non-null float64
7     56276 non-null float64
8     56276 non-null float64
9     56276 non-null float64
10    56276 non-null float64
11    56276 non-null float64
12    56276 non-null float64
13    56276 non-null float64
14    56276 non-null float64
15    56276 non-null float64
16    56276 non-null float64
17    56276 non-null float64
18    56276 non-null float64
19    56276 non-null float64
20    56276 non-null float64
dtypes: float64(21)
memory usage: 9.0 MB

In [14]:
# coverage = np.sum(pca.explained_variance_ratio_)
# coverage

0.904959649397919

In [29]:
reduced_data['RISKGR'] = y
reduced_data.head()

,0,1,2,3,4,5,6,7,8,9,...,253,254,255,256,257,258,259,260,261,RISKGR
0,4.161882,-9.325109,-0.373126,-0.052808,-0.698259,4.933511,-2.140699,0.869421,0.038036,0.954849,...,0.649631,-0.670733,-0.711541,-0.832681,-1.388345,0.117794,0.454118,-1.059230,0.423132,0
1,9.674925,-3.581752,-4.303914,-10.333025,5.763884,-6.214472,6.969558,-7.564769,0.817216,-3.354259,...,0.273793,-0.230721,0.423103,-0.637623,-0.790577,0.122406,0.007787,-0.214282,0.065505,2
2,10.236991,-6.791700,-3.447423,-10.103987,5.758740,-3.635738,5.683193,-7.229738,0.302514,-2.057853,...,-0.583463,0.072254,0.707858,-0.396691,0.453304,0.206835,-0.161873,0.628871,0.398236,2
3,3.540502,-10.364173,-2.053337,-2.910695,-0.762153,5.800408,-2.332828,0.825269,0.134046,-0.889574,...,-0.089045,-0.561901,0.211767,-0.305955,0.183721,0.090307,0.240883,0.435638,0.178456,2
4,-6.848046,-4.969237,11.457287,-0.199674,-5.355195,1.820314,0.473076,-3.146023,-1.440604,8.725895,...,-0.308272,0.091469,0.359798,-0.463577,-0.885558,-0.313491,0.438535,-0.455354,-0.039124,0

In [30]:
reduced_data.to_csv('..\\data\\nsduh_reduced.csv',index=False)

### Feature selection

In [31]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [50]:
# selector = SelectKBest(f_classif, k='all').fit(reduced_data, y)
# selected = selector.transform(reduced_data)

C:\Users\Daria\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw

In [1]:
# selector.scores_

In [41]:
# selected_data = selected_data.drop(24,axis=1)
# selected_data['RISKGR'] = y
# selected_data.head()

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split

In [34]:
x = reduced_data.drop('RISKGR',axis=1)
y = reduced_data['RISKGR']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=121)

In [35]:
selector = SelectFromModel(RandomForestClassifier(n_estimators = 100))
selector.fit(x_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [37]:
selector.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True, False,  True, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [39]:
selected_features= x_train.columns[(selector.get_support())]
selected_features

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        31,  33,  37,  38,  46,  47,  49,  56,  62,  66,  68,  90, 111, 130,
       145],
      dtype='object')

In [42]:
selected_data = pd.DataFrame(reduced_data, columns=selected_features)
selected_data.head()

,0,1,2,3,4,5,6,7,8,9,...,47,49,56,62,66,68,90,111,130,145
0,4.161882,-9.325109,-0.373126,-0.052808,-0.698259,4.933511,-2.140699,0.869421,0.038036,0.954849,...,-1.190483,-2.824339,3.167359,-3.178832,0.346790,-1.228007,1.065471,0.878802,-0.524535,-2.113034
1,9.674925,-3.581752,-4.303914,-10.333025,5.763884,-6.214472,6.969558,-7.564769,0.817216,-3.354259,...,1.640087,-0.690094,-2.467652,0.757646,-2.479028,1.250870,-0.187800,0.782315,1.082719,-1.035084
2,10.236991,-6.791700,-3.447423,-10.103987,5.758740,-3.635738,5.683193,-7.229738,0.302514,-2.057853,...,-1.399327,-0.136231,3.780495,-0.700051,1.722126,-0.432071,-1.128847,0.139280,2.258887,0.002736
3,3.540502,-10.364173,-2.053337,-2.910695,-0.762153,5.800408,-2.332828,0.825269,0.134046,-0.889574,...,-0.096196,-1.780968,1.478300,0.448580,0.376718,0.650684,0.897770,-0.871122,0.478922,-0.790794
4,-6.848046,-4.969237,11.457287,-0.199674,-5.355195,1.820314,0.473076,-3.146023,-1.440604,8.725895,...,0.561601,-0.299312,-0.144528,-0.160850,-0.024217,-0.645038,0.228098,0.446301,1.240489,-1.378620

In [43]:
selected_data['RISKGR'] = y
selected_data.head()

,0,1,2,3,4,5,6,7,8,9,...,49,56,62,66,68,90,111,130,145,RISKGR
0,4.161882,-9.325109,-0.373126,-0.052808,-0.698259,4.933511,-2.140699,0.869421,0.038036,0.954849,...,-2.824339,3.167359,-3.178832,0.346790,-1.228007,1.065471,0.878802,-0.524535,-2.113034,0
1,9.674925,-3.581752,-4.303914,-10.333025,5.763884,-6.214472,6.969558,-7.564769,0.817216,-3.354259,...,-0.690094,-2.467652,0.757646,-2.479028,1.250870,-0.187800,0.782315,1.082719,-1.035084,2
2,10.236991,-6.791700,-3.447423,-10.103987,5.758740,-3.635738,5.683193,-7.229738,0.302514,-2.057853,...,-0.136231,3.780495,-0.700051,1.722126,-0.432071,-1.128847,0.139280,2.258887,0.002736,2
3,3.540502,-10.364173,-2.053337,-2.910695,-0.762153,5.800408,-2.332828,0.825269,0.134046,-0.889574,...,-1.780968,1.478300,0.448580,0.376718,0.650684,0.897770,-0.871122,0.478922,-0.790794,2
4,-6.848046,-4.969237,11.457287,-0.199674,-5.355195,1.820314,0.473076,-3.146023,-1.440604,8.725895,...,-0.299312,-0.144528,-0.160850,-0.024217,-0.645038,0.228098,0.446301,1.240489,-1.378620,0

In [44]:
selected_data.to_csv('..\\data\\nsduh_selected.csv',index=False)

## TPOT to choose pipeline

In [45]:
from tpot import TPOTClassifier
from sklearn.model_selection import train_test_split

In [47]:
x = selected_data.drop('RISKGR',axis=1)
y = selected_data['RISKGR']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7, random_state=121)

In [48]:
pipeline_optimizer = TPOTClassifier(population_size=20, cv=5, random_state=42, 
                                    verbosity=2, early_stop = 7)
pipeline_optimizer.fit(x_train, y_train)
print(pipeline_optimizer.score(x_test, y_test))
pipeline_optimizer.export('tpot_exported_pipeline.py')

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.

HBox(children=(IntProgress(value=0, description='Optimization Progress', max=2020, style=ProgressStyle(descripâ€¦

Generation 1 - Current best internal CV score: 0.769045509057321
Generation 2 - Current best internal CV score: 0.769045509057321
Generation 3 - Current best internal CV score: 0.7702889884140027
Generation 4 - Current best internal CV score: 0.7710582007476287
Generation 5 - Current best internal CV score: 0.7710582007476287
Generation 6 - Current best internal CV score: 0.7733701539086049
Generation 7 - Current best internal CV score: 0.775857656715967
Generation 8 - Current best internal CV score: 0.775857656715967
Generation 9 - Current best internal CV score: 0.775857656715967
Generation 10 - Current best internal CV score: 0.7760341889824316
Generation 11 - Current best internal CV score: 0.776212370315163
Generation 12 - Current best internal CV score: 0.7772194092010802
Generation 13 - Current best internal CV score: 0.7772194092010802
Generation 14 - Current best internal CV score: 0.7772194092010802
Generation 15 - Current best internal CV score: 0.7780484244827728
Generation 16 - Current best internal CV score: 0.7780484244827728
Generation 17 - Current best internal CV score: 0.7780484244827728
Generation 18 - Current best internal CV score: 0.7780484244827728
Generation 19 - Current best internal CV score: 0.7781677853628421
Generation 20 - Current best internal CV score: 0.7781677853628421
Generation 21 - Current best internal CV score: 0.7781677853628421
Generation 22 - Current best internal CV score: 0.7781677853628421
Generation 23 - Current best internal CV score: 0.7781677853628421

The optimized pipeline was not improved after evaluating 7 more generations. Will end the optimization process.

TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: RandomForestClassifier(LogisticRegression(input_matrix, C=25.0, dual=False, penalty=l1), bootstrap=True, criterion=gini, max_features=0.3, min_samples_leaf=18, min_samples_split=19, n_estimators=100)
0.7807026450728537